### PR TITLE
add showcase

### PR DESCRIPTION
**Pull request by newaeonweb**
Added new showcase link.

### CODE REVIEW

**Comment by newaeonweb** [comment]
@LokeCarlsson as i saw is just the order, right? You can merge this way if don't mind. Thanks

**Comment by LokeCarlsson** [comment]
@newaeonweb Something is broken with the first link. Is it needed at all?

image

**Comment by newaeonweb** [comment]
@LokeCarlsson Hi, sorry for my delay. I think its ok now. Thanks

**Comment by LokeCarlsson** [comment]
@newaeonweb I'm pretty sure you shouldn't include introduction section and contents in contents. Please only add your showcase link and I can merge this. I think the contents section is fine as is.

**Comment by newaeonweb** [comment]
@LokeCarlsson yeah, i'll check it again, maybe my editor change something that i miss

**Comment by newaeonweb** [comment]
@LokeCarlsson, my editor was configured to use a markdown table of contents plugin. I'm so sorry for the inconvenience.

**Pull request merged**
